import { Delivery } from "./features/driverSlice";

export const del: Delivery[] = [
  {
    deliveryId: "DLV-001",
    orderId: "ORD-1001",
    orderDate: String(new Date("2025-11-05T10:30:00Z").toISOString()),
    deliveryDate: String(new Date("2025-11-06T14:00:00Z").toISOString()),
    customerName: "John Doe",
    payment: 1200,
    Pickup: "Gulshan 1",
    dropOff: "Banani 11",
    Distance: 4.2,
    Earning: 150,
    Company: "JVAI Logistics",
    Status: "delivered",
    Description: "Small electronics package",
    rating: 5,
    vehicle: "bike",
    weight: 1.2,
  },
  {
    deliveryId: "DLV-002",
    orderId: "ORD-1002",
    orderDate: String(new Date("2025-11-07T08:00:00Z").toISOString()),
    deliveryDate: String(new Date("2025-11-07T10:20:00Z").toISOString()),
    customerName: "Abdul Karim",
    payment: 2200,
    Pickup: "Mirpur 10",
    dropOff: "Dhanmondi 27",
    Distance: 8.5,
    Earning: 320,
    Company: "FastEx",
    Status: "pickedup",
    Description: "Groceries delivery",
    rating: 4,
    vehicle: "pickup",
    weight: 15,
  },
  {
    deliveryId: "DLV-003",
    orderId: "ORD-1003",
    orderDate: String(new Date("2025-11-08T09:15:00Z").toISOString()),
    deliveryDate: String(new Date("2025-11-08T13:45:00Z").toISOString()),
    customerName: "Mizanur Rahman",
    payment: 5000,
    Pickup: "Uttara Sector 7",
    dropOff: "Farmgate",
    Distance: 12,
    Earning: 600,
    Company: "CargoPro",
    Status: "trip",
    Description: "Furniture delivery",
    rating: 0,
    vehicle: "truck",
    weight: 80,
  },
  {
    deliveryId: "DLV-004",
    orderId: "ORD-1004",
    orderDate: String(new Date("2025-11-09T11:00:00Z").toISOString()),
    deliveryDate: String(new Date("2025-11-10T09:10:00Z").toISOString()),
    customerName: "Sarah Ali",
    payment: 900,
    Pickup: "Bashundhara R/A",
    dropOff: "Kuril Flyover",
    Distance: 3.1,
    Earning: 120,
    Company: "JVAI Logistics",
    Status: "pending",
    Description: "Food delivery",
    rating: 0,
    vehicle: "bike",
    weight: 0.5,
  },
  {
    deliveryId: "DLV-005",
    orderId: "ORD-1005",
    orderDate: String(new Date("2025-11-10T07:45:00Z").toISOString()),
    deliveryDate: String(new Date("2025-11-10T08:30:00Z").toISOString()),
    customerName: "David Singh",
    payment: 1800,
    Pickup: "TSC Dhaka University",
    dropOff: "Motijheel",
    Distance: 5.7,
    Earning: 230,
    Company: "FastEx",
    Status: "accepted",
    Description: "Document delivery",
    rating: 5,
    vehicle: "bike",
    weight: 0.3,
  }
];
