import { Food } from "./features/foodSlice";

export const foods:Food[]=[
  {
    id: "food_1",
    name: "Broccoli",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 34, protein: 2.82, carbs: 6.64, fats: 0.37 },
    approved: true,
  },
  {
    id: "food_2",
    name: "Spinach",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 23, protein: 2.86, carbs: 3.63, fats: 0.39 },
    approved: true,
  },
  {
    id: "food_3",
    name: "Cucumber",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 15, protein: 0.65, carbs: 3.63, fats: 0.11 },
    approved: true,
  },
  {
    id: "food_4",
    name: "Banana",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 89, protein: 1.09, carbs: 22.84, fats: 0.33 },
    approved: true,
  },
  {
    id: "food_5",
    name: "Apple",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 52, protein: 0.26, carbs: 13.81, fats: 0.17 },
    approved: true,
  },
  {
    id: "food_6",
    name: "Orange",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 47, protein: 0.94, carbs: 11.75, fats: 0.12 },
    approved: true,
  },
  {
    id: "food_7",
    name: "Avocado",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 167, protein: 1.96, carbs: 8.64, fats: 15.41 },
    approved: true,
  },
  {
    id: "food_8",
    name: "Peanut Butter",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 587, protein: 24.35, carbs: 21.26, fats: 49.66 },
    approved: true,
  },
  {
    id: "food_9",
    name: "Almond",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 579, protein: 21.15, carbs: 21.55, fats: 49.93 },
    approved: true,
  },
  {
    id: "food_10",
    name: "Chia Seed",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 486, protein: 16.54, carbs: 42.12, fats: 30.74 },
    approved: true,
  },
  {
    id: "food_11",
    name: "Full-Fat Milk",
    addedBy: "system",
    selectedBy: 0,
    unit: "ml",
    nutrition: { calories: 61, protein: 3.15, carbs: 4.8, fats: 3.25 },
    approved: true,
  },
  {
    id: "food_12",
    name: "Yogurt (Tok Doi)",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 61, protein: 3.47, carbs: 4.66, fats: 3.25 },
    approved: true,
  },
  {
    id: "food_13",
    name: "Cheddar Cheese Slice",
    addedBy: "system",
    selectedBy: 0,
    unit: "slice",
    nutrition: { calories: 77.9, protein: 4.61, carbs: 0.4, fats: 6.43 },
    approved: true,
  },
  {
    id: "food_14",
    name: "Egg (with yolk)",
    addedBy: "system",
    selectedBy: 0,
    unit: "piece",
    nutrition: { calories: 71.5, protein: 6.28, carbs: 0.36, fats: 4.76 },
    approved: true,
  },
  {
    id: "food_15",
    name: "Egg White",
    addedBy: "system",
    selectedBy: 0,
    unit: "piece",
    nutrition: { calories: 17, protein: 3.64, carbs: 0.24, fats: 0.6 },
    approved: true,
  },
  {
    id: "food_16",
    name: "Chicken / Fish",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 173, protein: 30.91, carbs: 0, fats: 4.51 },
    approved: true,
  },
  {
    id: "food_17",
    name: "Beef",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 250, protein: 26.72, carbs: 0, fats: 15.11 },
    approved: true,
  },
  {
    id: "food_18",
    name: "Butter",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 717, protein: 0.85, carbs: 0.6, fats: 81.11 },
    approved: true,
  },
  {
    id: "food_19",
    name: "Olive Oil",
    addedBy: "system",
    selectedBy: 0,
    unit: "ml",
    nutrition: { calories: 884, protein: 0, carbs: 0, fats: 100 },
    approved: true,
  },
  {
    id: "food_20",
    name: "Isubgol (Psyllium Husk)",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 5.58, protein: 0.13, carbs: 0, fats: 0.01 },
    approved: true,
  },
  {
    id: "food_21",
    name: "Multivitamin A-Z",
    addedBy: "system",
    selectedBy: 0,
    unit: "piece",
    nutrition: { calories: 0, protein: 0, carbs: 0, fats: 0 },
    approved: true,
  },
  {
    id: "food_22",
    name: "Fish Oil Capsule",
    addedBy: "system",
    selectedBy: 0,
    unit: "piece",
    nutrition: { calories: 10.2, protein: 0, carbs: 0.1, fats: 1 },
    approved: true,
  },
  {
    id: "food_23",
    name: "Cooked Rice",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 130, protein: 2.69, carbs: 28.17, fats: 0.28 },
    approved: true,
  },
  {
    id: "food_24",
    name: "Biscuit / Rusk / Cracker",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 408.87, protein: 11.82, carbs: 72.43, fats: 7.28 },
    approved: true,
  },
  {
    id: "food_25",
    name: "Oats",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 379, protein: 13.15, carbs: 67.7, fats: 6.52 },
    approved: true,
  },
  {
    id: "food_26",
    name: "Roti (Flatbread)",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 285.12, protein: 8.47, carbs: 46.13, fats: 9.2 },
    approved: true,
  },
  {
    id: "food_27",
    name: "Lentil (Moshur Dal)",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 358, protein: 23.91, carbs: 63.1, fats: 2.17 },
    approved: true,
  },
  {
    id: "food_28",
    name: "Sugar",
    addedBy: "system",
    selectedBy: 0,
    unit: "gram",
    nutrition: { calories: 387, protein: 0, carbs: 99.98, fats: 0 },
    approved: true,
  },
];
